### ISSUE TITLE
LIT demo notebook not working

### ISSUE THREAD

**Issue by dppalukuri** [PAIR-code/lit#1350] opened 2023-10-25 13:33 UTC
Hi,

I am trying to run the below demo notebook, but the widget is not rendering.
https://colab.research.google.com/github/PAIR-code/lit/blob/main/lit_nlp/examples/notebooks/LIT_sentiment_classifier.ipynb

I am faced with this error.
![image](https://github.com/PAIR-code/lit/assets/69419325/3b4bf9ea-97fd-41cd-ad23-b8f745fee14d)

If anyone was able to run the demo or was able to use LIT visualization on any kind of classifier on opensource data, please share your source code.
Thanks in advance for your help!

**Comment by jameswex** [comment] 2023-10-25 14:14
Thanks, I am able to repro this issue and we're looking into it.

**Comment by ShamzGuy** [comment] 2023-11-02 06:54
![image](https://github.com/PAIR-code/lit/assets/7983666/092fcd46-9e6a-433f-840f-4b4664c2228d)
Getting the same issue. Could you please help?

**Comment by jameswex** [comment] 2023-11-02 13:06
The issue actually seems to be with chrome and colab and is affecting other in-colab web apps such as TensorBoard. The colab team is actively looking into the issue.

**Comment by jameswex** [comment] 2023-11-02 18:58
https://bugs.chromium.org/p/chromium/issues/detail?id=1498580 seems to be the root cause issue

**Comment by jameswex** [comment] 2023-11-07 18:25
I have a solution to fix this issue and will get a new pip package released with the update hopefully later this week.

**Comment by dppalukuri** [comment] 2023-11-08 06:12
That'll be great!  tysm!

**Comment by jameswex** [comment] 2023-11-08 16:48
We have release lit-nlp 1.0.2 on pypi with https://github.com/PAIR-code/lit/pull/1357 to fix the colab rendering issue.  Please let me know if this solves your issue.

Note that when testing this, I did see some python version issues between LIT's requirements and colab's python version (which seem to exist with our old pip package as well), which required me to test this pip package by doing the following install
```
!pip install --no-deps lit-nlp
!pip install sacrebleu rouge_score ml_collections transformers
```
instead of just installing lit-nlp and letting it install its dependencies.

**Comment by ShamzGuy** [comment] 2023-11-09 04:45
Thanks @jameswex  it's working now!

**Closed** 2023-11-09 13:54 UTC
