### ISSUE TITLE
Unknown error while running prompt debugging example

### ISSUE THREAD

**Issue by TehreemFarooqi** [PAIR-code/lit#1595] opened 2024-12-12 13:29 UTC
I am running the Colab notebook shared in the [Sequence Salience tutorial](https://pair-code.github.io/lit/tutorials/sequence-salience/).

When I click a prompt from the data table, it shows unknown error below the UI and gets stuck in a loading loop. Does not show an error or anything.

![image](https://github.com/user-attachments/assets/570e6a5d-1c98-4d2e-a851-cefa4000db9b)

I have access to Gemma model on Kaggle and I have done all other pre-requisite steps. How can I run LIT with the Gemma models?

**Comment by TehreemFarooqi** [comment] 2024-12-12 13:31
Kind of in a crunch, hopefully @RyanMullins can help me please?

**Comment by RyanMullins** [comment] 2024-12-12 13:50
Usually the unknown error means that the model is taking too long to respond and the HTTP request timed out. The server is still running in the background though, and is caching results as they come back from the model, so that you can come back to it after 5 minutes or so. 

Can you share more about the setup you're using, specifically the Gemma variant and GPU/accelerator you're connected to? 

The alternative to Colab is running LIT and the models you want to interpret in a container on a cloud platform. We have step-by-step instructions for running [LIT on Google Cloud](https://codelabs.developers.google.com/codelabs/responsible-ai/lit-on-gcp) that can be adapted to other provides (e.g., AWS, Azure) as necessary.

**Comment by TehreemFarooqi** [comment] 2024-12-12 13:59
Thanks for your reply. I am connected to Colab free version, T4 GPU. The tutorial mentioned that Gemma 2B can run on T4 GPU. Can I run this if I upgrade to Colab pro and use a better GPU or Colab just can't handle this kind of processing?

**Comment by RyanMullins** [comment] 2024-12-12 14:29
Thanks for the context. Some follow-up questions:

* Are you using the demo dataset that comes with the LIT Colab or are you loading your own? If loading your own, how big is that dataset? 
* Is the Colab kernel crashing and rebooting at all?

I think it's most likely that this is related to a known issue in the `DataService` that backs the LIT web app, but it could be related to out-of-memory issues on the GPU.

If the kernel is crashing and restarting, then it's an OOM issue and you should consider either [upgrading to Colab Pro](https://colab.research.google.com/signup) to get access to something with more headroom (e.g., an A100) or using [LIT on Google Cloud](https://codelabs.developers.google.com/codelabs/responsible-ai/lit-on-gcp). 

If you're not seeing kernel crashes or restarts, then I'm pretty confident it's related to the `DataService` fetching _everything_ on first load/interaction instead of only loading the example you're interested in. This pattern was fine for LIT before billion-parameter GenAI models, but it's not scaling to Gemma in a way we're happy with. We're working on a proper fix for this, but it's considerably more complicated than we expected and we don't have an ETA for this landing right now. We do have two potential workarounds: 

* Pass `warm_start=True` in the the `lit_pdbnb.make_notebook_widget()` call so that it doesn't return with a render-able widget until the [entire dataset](https://pair-code.github.io/lit/documentation/faq.html#dataset-size) has been run through the model.
* Do what you're doing and wait for the server to finish/stabilize after that first interaction and then come back to it.

**Comment by TehreemFarooqi** [comment] 2024-12-12 14:36
- Using the sample dataset that comes with LIT Colab.
- No, the kernel doesn't crash or restart

Thanks for the detailed response. I think for now I will move to Google Cloud. Will try warm_start later.

For the workarounds, I did try waiting for the server to stabilize and giving it time but it's not working for me even after some time and seems to be stuck on loading. Maybe need to wait longer. Thanks for all your help!

**Comment by RyanMullins** [comment] 2024-12-13 14:47
Hi @TehreemFarooqi!

I'm re-opening this issue because we have been talking to https://github.com/mattdangerw from the https://github.com/keras-team/keras-hub team and you might have actually found a bug (likely in LIT, possibly in Keras Hub). 

Can you please confirm the values you're passing into the `make_notebook_widget()` call in your notebook? 

For documentation purposes, the default values from [the notebook](https://colab.research.google.com/github/google/generative-ai-docs/blob/main/site/en/gemma/docs/lit_gemma.ipynb#scrollTo=BdgJqj56QSOC) are as follows:

```python
lit_widget = lit_pdbnb.make_notebook_widget(
    ['sample_prompts'],
    ["gemma_2b_it:gemma_1.1_instruct_2b_en"],
    dl_framework="kerasnlp",
    dl_runtime="tensorflow",
    batch_size=1,
    max_examples=5,
    precision="bfloat16",
)
```

**Comment by TehreemFarooqi** [comment] 2024-12-13 17:42
Hi @RyanMullins, so I actually used the default values in the notebook as it is. I was just trying to run a simple example to see LIT's working.

Maybe that is the reason I have not been able to run LIT on google cloud even with GPT2? Maybe I should move to HuggingFace for now to resolve the issue?

**Comment by RyanMullins** [comment] 2024-12-13 18:00
Thanks, that's helpful. 

Yes, please try `dl_framework='huggingface'` and `dl_runtime='torch'` and let me know how it goes.

**Comment by TehreemFarooqi** [comment] 2024-12-13 18:49
So doing that didn't help and I still got unknown error. But I experimented with different changes and weirdly enough:

`pip install "tensorflow==2.17"`

```
lit_widget = lit_pdbnb.make_notebook_widget(
    ['sample_prompts'],
    ["gemma_2b_it:gemma_1.1_instruct_2b_en"],
    dl_framework="kerasnlp",
    dl_runtime="tensorflow",
)
```

These changes make it work.

**Comment by RyanMullins** [comment] 2024-12-13 19:05
Thanks for running that, @TehreemFarooqi. You're findings are complementing what we're finding and helping us identify the root cause. Will keep you posted as we dig further.

**Comment by bdu91** [comment] 2024-12-20 21:53
We have fixed the issue and released a minor update. As tested, the [Sequence Salience tutorial](https://pair-code.github.io/lit/tutorials/sequence-salience/) works now without any additional modifications. So closing this thread.

**Closed as completed by bdu91** 2024-12-20 21:53 UTC
