### ISSUE TITLE
Adding an entry in "Datapoint Editor" causes "Data Table" to jump to 1st page of results

### ISSUE THREAD

**Issue by itstommygunn** [PAIR-code/lit#851] opened 2022-09-06 12:21 UTC
Hello,

1) Load dataset, in Data Table jump to a further page of results,
2) Select a sentence, in Datapoint Editor change label, click "Add",
3) This caused Data Table to jump to 1st page of results, causing some inconvenience

First time opening an issue on github - sorry if the issue's not very elegant.

Thanks!

**Comment by jameswex** [comment] 2022-09-06 13:38
Thanks so much, @itstommygunn 

I've added this issue to our internal bug tracking list as well to ensure we fix this inconvenience.

**Comment by itstommygunn** [comment] 2022-09-08 07:31
@jameswex , Could you please kindly advise how to delete a mistakenly added entry?

1. Select a sentence, in Datapoint Editor change label, click "Add". 
2. Trying to figure out a way of removing such entry

Thanks a million,

**Comment by jameswex** [comment] 2022-09-08 12:05
we don't currently have a way to delete an entry from the data table, but these added datapoints are ephemeral by design. if you reload the page, you will only see the original dataset loaded at start-up time.

**Comment by RyanMullins** [comment] 2022-10-18 20:07
Hi @itstommygunn,

If you haven't yet, please try using the `dev` branch to see if you can reproduce this. I believe I fixed it back in 91218b2. There was one lingering issue that I'm fixing if you added a datapoint while you were on the last page of the Data Table module. Expect that fix on `dev` today or tomorrow (19 Oct 2022).

**Comment by RyanMullins** [comment] 2023-05-03 17:36
This was fixed in LIT v0.5. Closing.

**Closed by RyanMullins** 2023-05-03 17:36 UTC
